baseURL: "https://vedanthvbaliga.netlify.app/"
languageCode: en-us
title: Vedanth V Baliga
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 20
    - identifier: experience
      name: Experience
      url: /experience
      weight: 30
    - identifier: blog
      name: Blog
      url: /blog
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Vedanth V Baliga"
    subtitle: Junior Year Computer Science Undergrad | **Kaggle Expert**<br> Dabbling with Data Science <br> Loves Building **End to End ML Solutions** For Real World Problems
    imageUrl: "home/me.jpg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1mfkM-k4RbixuqWqgLwgr-kVa8HqXP9cb/view"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:vedanthvbaliga@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/vedanthbaliga/"
    - name: "github"
      url: "https://github.com/vedanthv"
    # - name: "cv"
    #   url: "https://drive.google.com/file/d/1mfkM-k4RbixuqWqgLwgr-kVa8HqXP9cb/view"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
